# Generated by Django 3.0.5 on 2023-03-10 21:41

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('image', common.models.MyImageField(default='', max_length=255, verbose_name='图片')),
                ('url', models.CharField(default='', max_length=255, verbose_name='连接地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'picture',
            },
        ),
    ]
