# Generated by Django 3.2.5 on 2023-03-15 00:05

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'picture', 'verbose_name_plural': 'picture'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=common.models.MyImageField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='url'),
        ),
    ]
