# Generated by Django 3.2.5 on 2023-03-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230315_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=8, verbose_name='sex'),
        ),
    ]
