# Generated by Django 3.2.5 on 2023-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(default='', max_length=50, verbose_name='tabel')),
                ('tableid', models.IntegerField(default=0, verbose_name='tableid')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('score', models.CharField(default='', max_length=255, verbose_name='score')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('author', models.CharField(db_column='author', default='', max_length=50, verbose_name='author')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='addtime')),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issue',
                'db_table': 'issues',
            },
        ),
    ]
