# Generated by Django 3.2.5 on 2023-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', default='', max_length=50, verbose_name='username')),
                ('xwid', models.IntegerField(default=0, verbose_name='xwid')),
                ('tabele', models.CharField(default='', max_length=50, verbose_name='table')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='addtime')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collection',
                'db_table': 'collection',
            },
        ),
    ]
