# Generated by Django 3.2.5 on 2023-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_tabele_collection_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='xwid',
        ),
        migrations.AddField(
            model_name='collection',
            name='movie_id',
            field=models.IntegerField(default=0, verbose_name='movie_id'),
        ),
    ]
