# Generated by Django 3.2.5 on 2023-03-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '__first__'),
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colums',
            new_name='Columns',
        ),
    ]
