# Generated by Django 3.2.5 on 2023-03-15 02:03

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('colum', models.IntegerField(db_column='colum', default=1)),
                ('director', models.CharField(default='', max_length=50, verbose_name='director')),
                ('actor', models.TextField(default='', verbose_name='actor')),
                ('date', models.CharField(default='', max_length=10, verbose_name='date')),
                ('video', models.FileField(default='', upload_to='', verbose_name='video')),
                ('pic', common.models.MyImageField(default='', max_length=255, verbose_name='pic')),
                ('tags', models.TextField(default='', verbose_name='tags')),
                ('collection_count', models.IntegerField(default=0, verbose_name='collection_count')),
                ('visit_count', models.IntegerField(default=0, verbose_name='visit_count')),
                ('issues_count', models.IntegerField(default=0, verbose_name='issues_count')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='score')),
                ('intro', common.models.UMeditorField(default='', verbose_name='intro')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='addtime')),
                ('imdb', models.URLField(max_length=128)),
                ('time_length', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'movies',
                'verbose_name_plural': 'movies',
                'db_table': 'movies',
            },
        ),
    ]
