# Generated by Django 3.2.5 on 2023-03-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
