# Generated by Django 3.2.5 on 2023-03-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
